pass_dic= {
    "A" : "`fg:d7%UFH+y",
    "B" : "W]J`/XnEN@s,",
    "C" : "K(cRs8Jd5okV",
    "D" : "+8Pz=,5N}\dC",
    "E" : "?5y;<&4Uql-t",
    "F" : "?96Cs#}!bZVL",
    "G" : "P+[Zr>L,wR%F",
    "H" : "H{KIYr?M5;p0",
    "I" : "%j,Gl3w(QYto",
    "0" : "Wh>%np/B6HRa",
    "1" : "3H4B`b!th)=:",
    "2" : "_Z#XN,[]{3t*",
    "3" : "!tGA`R:Ydwpe",
    "4" : "~-cATD]W8fC[",
    "5" : "FhbZp)8z&Aak",
    "6" : "aFtO#gS@HD>h",
    "7" : "fLU>DjNPh6dZ",
    "8" : "qP@?A5cRLfC6",
    "9" : "OKX)g`#DJi}d",
    "J" : "-M&L~Wo)`aO9",
    "K" : ":W@!<?EPeTNJ",
    "L" : "B1yE~:#}9RL?",
    "M" : "h2$y(NTR)0k8",
    "N" : "JdwT-A?4$Wm`",
    "O" : ":aCB;wy296ib",
    "P" : "ej!Cf;8tzwp7",
    "Q" : "3@bom-iMt!VN",
    "R" : "{UCt&PDRsb95",
    "S" : "}S`_mr=[o4Zg",
    "T" : "eFVS`a@-gT6[",
    "U" : "6nX,]qd`u\=O",
    "V" : "]&Ao@lx3Gphy",
    "W" : "=WgdyMaf#iC7",
    "X" : "Dq7wPLG0IEJ#",
    "Y" : "~a5/`U%HcRgV",
    "Z" : ">9oHC-NQl7_h",
    "a" : "/N*pQKeCfn(#",
    "b" : "Kq4iP]7T&D#3",
    "c" : "=32pCt8+NyQY",
    "d" : "NSks?Fom6IDH",
    "e" : "XhBuS>cU*k3m",
    "f" : "%*/iZaOsld$K",
    "g" : "d6N0MWjfZqKk",
    "h" : "5A4}/N@Jafx_",
    "i" : "Gla4;s1ob>W=",
    "j" : "Kc#Y$`RG2m1w",
    "k" : "$d>s35ofUtyw",
    "l" : "j]cH3NL!hW/y",
    "m" : "dzv_m@1U]3cH",
    "n" : "~=fN$hm->e5s",
    "o" : "X_CSVkPg$+yo",
    "p" : "6?/tS[9!FkdE",
    "q" : "1Qv}6:KDq&\X",
    "r" : "Q<1hxiyE_vB>",
    "s" : "8i>X<F2M*(dl",
    "t" : "QIoE+4{yHM/?",
    "u" : "dJkNizc3Opw/",
    "v" : ">)35I2ej&r6E",
    "w" : "PMcYbjU@6RWn",
    "x" : "R2Bb]&<OMqHn",
    "y" : "Cq%}IPRb*[4$",
    "z" : "b7v:ENd\8nf}",
    "_" : "Mve5`CUY)]B*",
    "$" : "24%<U0mEV:6x",
    "#" : "AESGNC-T1dsI",
    "!" : "!0aM_%P:[&>*"
}

pass_dic_inv = {
   "`fg:d7%UFH+y" : "A",
   "W]J`/XnEN@s," : "B",
   "K(cRs8Jd5okV" : "C",
   "+8Pz=,5N}\dC" : "D",
   "?5y;<&4Uql-t" : "E",
   "?96Cs#}!bZVL" : "F",
   "P+[Zr>L,wR%F" : "G",
   "H{KIYr?M5;p0" : "H",
   "%j,Gl3w(QYto" : "I",
   "Wh>%np/B6HRa" : "0",
   "3H4B`b!th)=:" : "1",
   "_Z#XN,[]{3t*" : "2",
   "!tGA`R:Ydwpe" : "3",
   "~-cATD]W8fC[" : "4",
   "FhbZp)8z&Aak" : "5",
   "aFtO#gS@HD>h" : "6",
   "fLU>DjNPh6dZ" : "7",
   "qP@?A5cRLfC6" : "8",
   "OKX)g`#DJi}d" : "9",
   "-M&L~Wo)`aO9" : "J",
   ":W@!<?EPeTNJ" : "K",
   "B1yE~:#}9RL?" : "L",
   "h2$y(NTR)0k8" : "M",
   "JdwT-A?4$Wm`" : "N",
   ":aCB;wy296ib" : "O",
   "ej!Cf;8tzwp7" : "P",
   "3@bom-iMt!VN" : "Q",
   "{UCt&PDRsb95" : "R",
   "}S`_mr=[o4Zg" : "S",
   "eFVS`a@-gT6[" : "T",
   "6nX,]qd`u\=O" : "U",
   "]&Ao@lx3Gphy" : "V",
   "=WgdyMaf#iC7" : "W",
   "Dq7wPLG0IEJ#" : "X",
   "~a5/`U%HcRgV" : "Y",
   ">9oHC-NQl7_h" : "Z",
   "/N*pQKeCfn(#" : "a",
   "Kq4iP]7T&D#3" : "b",
   "=32pCt8+NyQY" : "c",
   "NSks?Fom6IDH" : "d",
   "XhBuS>cU*k3m" : "e",
   "%*/iZaOsld$K" : "f",
   "d6N0MWjfZqKk" : "g",
   "5A4}/N@Jafx_" : "h",
   "Gla4;s1ob>W=" : "i",
   "Kc#Y$`RG2m1w" : "j",
   "$d>s35ofUtyw" : "k",
   "j]cH3NL!hW/y" : "l",
   "dzv_m@1U]3cH" : "m",
   "~=fN$hm->e5s" : "n",
   "X_CSVkPg$+yo" : "o",
   "6?/tS[9!FkdE" : "p",
   "1Qv}6:KDq&\X" : "q",
   "Q<1hxiyE_vB>" : "r",
   "8i>X<F2M*(dl" : "s",
   "QIoE+4{yHM/?" : "t",
   "dJkNizc3Opw/" : "u",
   ">)35I2ej&r6E" : "v",
   "PMcYbjU@6RWn" : "w",
   "R2Bb]&<OMqHn" : "x",
   "Cq%}IPRb*[4$" : "y",
   "b7v:ENd\8nf}" : "z",
   "Mve5`CUY)]B*" : "_",
   "24%<U0mEV:6x" : "$",
   "AESGNC-T1dsI" : "#",
   "!0aM_%P:[&>*" : "!"
}

def encrypt(string):
    temp_str = ''
    for i in string:
        temp_str+=pass_dic.get(i)
    return temp_str


def decrypt(string):
    tempo = ""
    for j in range(0, len(string), 12):
        temp = string[j:j+12]
        tempo+=pass_dic_inv.get(temp)
    return tempo
